<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>org.apache</groupId>
        <artifactId>apache</artifactId>
        <version>37</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <groupId>org.apache.tomcat.maven</groupId>
    <artifactId>tomcat-maven-plugin</artifactId>
    <packaging>maven-plugin</packaging>
    <name>Apache Tomcat Maven Plugin</name>
    <!-- Tomcat 9, 10 and 11 are supported -->
    <version>9.0.117</version>
    <description>The Tomcat Maven Plugin provides goals to manipulate WAR
        projects within the Tomcat servlet
        container.
    </description>

    <url>${siteUrl}</url>

    <properties>

        <!-- Tomcat version derives from the plugin version -->
        <tomcatVersion>${project.version}</tomcatVersion>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <mavenVersion>3.8.1</mavenVersion>

        <mavenPluginPluginVersion>3.15.2</mavenPluginPluginVersion>
        <!-- Test settings -->
        <maven.test.redirectTestOutputToFile>false</maven.test.redirectTestOutputToFile>
        <surefire.version>3.5.5</surefire.version>
        <failsafe.version>${surefire.version}</failsafe.version>

        <junit.version>4.13.2</junit.version>
        <it.sleep.time>2000</it.sleep.time>
        <verifier.maven.debug>false</verifier.maven.debug>
        <verifier.debugJvm>false</verifier.debugJvm>
        <distributionReleaseUrl>https://repository.apache.org/service/local/staging/deploy/maven2</distributionReleaseUrl>

        <distributionSnapshotsUrl>https://repository.apache.org/content/repositories/snapshots</distributionSnapshotsUrl>
        <distributionIdSnapshots>apache.snapshots.https</distributionIdSnapshots>

        <distributionSiteUrl>
            scp://people.apache.org/www/tomcat.apache.org/maven-plugin-${project.version}</distributionSiteUrl>
        <sitePath>maven-plugin-trunk</sitePath>
        <siteUrl>http://tomcat.apache.org/${sitePath}</siteUrl>

        <!-- http port used to run it test -->
        <its.http.port>1973</its.http.port>
        <!-- https port used to run it test -->
        <its.https.port>2003</its.https.port>
        <!-- ajp port used to run it test -->
        <its.ajp.port>2001</its.ajp.port>
        <!-- server port for it tests -->
        <its.server.port>2008</its.server.port>

        <!-- to prevent isssues with last apache parent pom -->
        <arguments />

        <tomcat-maven.siteFilePath>${user.home}/tomcat-maven-plugin-${project.version}/</tomcat-maven.siteFilePath>
        <tomcat-maven.siteUrlDeployment>file://${tomcat-maven.siteFilePath}</tomcat-maven.siteUrlDeployment>
        <tomcat-maven.scmPubCheckoutDirectory>${user.home}/tomcat-maven-plugin-${project.version}-content</tomcat-maven.scmPubCheckoutDirectory>
        <managerWebAppPath>${basedir}/target/</managerWebAppPath>

    </properties>

    <prerequisites>
        <maven>${mavenVersion}</maven>
    </prerequisites>
    <inceptionYear>2005</inceptionYear>

    <developers>
        <developer>
            <id>mhobson</id>
            <name>Mark Hobson</name>
            <email>markhobson@gmail.com</email>
            <roles>
                <role>Lead Developer</role>
            </roles>
            <timezone>0</timezone>
        </developer>
        <developer>
            <id>olamy</id>
            <name>Olivier Lamy</name>
            <email>olamy@apache.org</email>
        </developer>
    </developers>

    <contributors>
        <contributor>
            <name>Jurgen Lust</name>
        </contributor>
        <contributor>
            <name>Spike Washburn</name>
        </contributor>
        <contributor>
            <name>Mark Michaelis</name>
        </contributor>
        <contributor>
            <name>Peter Lynch</name>
        </contributor>
        <contributor>
            <name>Neale Upstone</name>
        </contributor>
        <contributor>
            <name>Tony Chemit</name>
        </contributor>
        <contributor>
            <name>Nigel Sim.</name>
        </contributor>
        <contributor>
            <name>Josh Harness</name>
        </contributor>
        <contributor>
            <name>Patrick Garcia</name>
        </contributor>
        <contributor>
            <name>Robin Bohm</name>
        </contributor>
        <contributor>
            <name>Mitch Kyle</name>
        </contributor>
        <contributor>
            <name>Glen Mazza</name>
        </contributor>
        <contributor>
            <name>Ludwig Magnusson</name>
        </contributor>
        <contributor>
            <name>Tim Astle</name>
        </contributor>
        <contributor>
            <name>Eugenio Santoboni</name>
        </contributor>
        <contributor>
            <name>Emeric MARTINEAU</name>
        </contributor>
        <contributor>
            <name>Daniel Cassidy</name>
        </contributor>
        <contributor>
            <name>Petar Tahchiev</name>
        </contributor>
        <contributor>
            <name>Denis Yudin</name>
        </contributor>
        <contributor>
            <name>Ryan Highley</name>
        </contributor>
        <contributor>
            <name>Cedric Dutoit</name>
        </contributor>
        <contributor>
            <name>Robert Hollencamp</name>
        </contributor>
        <contributor>
            <name>Michael Osipov</name>
        </contributor>
        <contributor>
            <name>Matthias Gunther</name>
        </contributor>
        <contributor>
            <name>Sylvain Guillope</name>
        </contributor>
        <contributor>
            <name>Dennis Lundberg</name>
        </contributor>
        <contributor>
            <name>Nicholas Albion</name>
        </contributor>
        <contributor>
            <name>Joshua Chaitin-Pollak</name>
        </contributor>
        <contributor>
            <name>Andrey Utkin</name>
        </contributor>
        <contributor>
            <name>John Gregg</name>
        </contributor>
        <contributor>
            <name>Xavier Dury</name>
        </contributor>
        <contributor>
            <name>Rupert Madden-Abbott</name>
        </contributor>
    </contributors>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <mailingLists>
        <mailingList>
            <name>User List</name>
            <subscribe>users-subscribe@tomcat.apache.org</subscribe>
            <unsubscribe>users-unsubscribe@tomcat.apache.org</unsubscribe>
            <post>users@tomcat.apache.org</post>
            <archive>http://mail-archives.apache.org/mod_mbox/tomcat-users/</archive>
            <otherArchives>
                <otherArchive>http://marc.info/?l=tomcat-user</otherArchive>
                <otherArchive>http://markmail.org/list/org.apache.tomcat.user/</otherArchive>
                <otherArchive>http://old.nabble.com/Tomcat---User-f342.html</otherArchive>
                <otherArchive>
                    http://www.mail-archive.com/users@tomcat.apache.org/</otherArchive>
            </otherArchives>
        </mailingList>

        <mailingList>
            <name>Development List</name>
            <subscribe>dev-subscribe@tomcat.apache.org</subscribe>
            <unsubscribe>dev-unsubscribe@tomcat.apache.org</unsubscribe>
            <post>dev@tomcat.apache.org</post>
            <archive>http://mail-archives.apache.org/mod_mbox/tomcat-dev/</archive>
            <otherArchives>
                <otherArchive>http://marc.info/?l=tomcat-dev</otherArchive>
                <otherArchive>http://markmail.org/list/org.apache.tomcat.dev/</otherArchive>
                <otherArchive>http://old.nabble.com/Tomcat---Dev-f341.html</otherArchive>
                <otherArchive>http://www.mail-archive.com/dev@tomcat.apache.org/</otherArchive>
            </otherArchives>
        </mailingList>

        <mailingList>
            <name>Announcements List</name>
            <subscribe>announce-subscribe@tomcat.apache.org</subscribe>
            <unsubscribe>announce-unsubscribe@tomcat.apache.org</unsubscribe>
            <post>N/A</post>
            <archive>http://mail-archives.apache.org/mod_mbox/tomcat-announce/</archive>
            <otherArchives>
                <otherArchive>http://marc.info/?l=tomcat-announce</otherArchive>
                <otherArchive>http://markmail.org/list/org.apache.tomcat.announce/</otherArchive>
                <otherArchive>http://www.mail-archive.com/announce@tomcat.apache.org/</otherArchive>
            </otherArchives>
        </mailingList>

    </mailingLists>

    <scm>
        <connection>scm:git:https://github.com/apache/tomcat-maven-plugin.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:apache/tomcat-maven-plugin.git</developerConnection>
        <url>https://github.com/apache/tomcat-maven-plugin</url>
    </scm>

    <issueManagement>
        <system>jira</system>
        <url>https://issues.apache.org/jira/browse/MTOMCAT</url>
    </issueManagement>

    <ciManagement>
        <url>https://builds.apache.org/job/TomcatMavenPlugin/</url>
    </ciManagement>

    <build>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
            </testResource>
        </testResources>
        <pluginManagement>
            <plugins>
                <!-- Override settings inherited from parent POM -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-antrun-plugin</artifactId>
                    <executions>
                        <execution>
                            <phase>pre-integration-test</phase>
                            <goals>
                                <goal>run</goal>
                            </goals>
                            <configuration>
                                <target>
                                    <unzip src="src/test/manager.war" dest="${managerWebAppPath}" />
                                </target>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <encoding>${project.build.sourceEncoding}</encoding>
                        <source>${maven.compiler.source}</source>
                        <target>${maven.compiler.target}</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${surefire.version}</version>
                    <configuration>
                        <excludes>
                            <exclude>**/**IT*</exclude>
                        </excludes>
                        <systemPropertyVariables>
                            <java.io.tmpdir>${project.build.directory}</java.io.tmpdir>
                        </systemPropertyVariables>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${failsafe.version}</version>
                    <configuration>
                        <excludes>
                            <exclude>**/deploy-only-war-project/**</exclude>
                            <exclude>**/deploy-war-project/**</exclude>
                            <exclude>**/simple-war-project/**</exclude>
                            <exclude>**/tomcat-run-multi-config/**</exclude>
                            <exclude>**/Abstract*.java</exclude>
                        </excludes>
                        <systemPropertyVariables>
                            <mojoVersion>${project.version}</mojoVersion>
                            <verifier.maven.debug>${verifier.maven.debug}</verifier.maven.debug>
                            <verifier.debugJvm>${verifier.debugJvm}</verifier.debugJvm>
                            <its.http.port>${its.http.port}</its.http.port>
                            <its.https.port>${its.https.port}</its.https.port>
                            <its.ajp.port>${its.ajp.port}</its.ajp.port>
                            <its.server.port>${its.server.port}</its.server.port>
                            <java.io.tmpdir>${project.build.directory}</java.io.tmpdir>
                        </systemPropertyVariables>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>integration-test</goal>
                                <goal>verify</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-invoker-plugin</artifactId>
                    <executions>
                        <execution>
                            <goals>
                                <goal>integration-test</goal>
                            </goals>
                            <configuration>
                                <pomIncludes>
                                    <include>**/simple-war-exec-project/pom.xml</include>
                                </pomIncludes>
                                <showErrors>true</showErrors>
                                <localRepositoryPath>${basedir}/target/it-repo</localRepositoryPath>
                                <settingsFile>src/it/settings.xml</settingsFile>
                                <postBuildHookScript>verify</postBuildHookScript>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-install-plugin</artifactId>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-plugin-plugin</artifactId>
                    <configuration>
                        <skipErrorNoDescriptorsFound>true</skipErrorNoDescriptorsFound>
                    </configuration>
                    <executions>
                        <execution>
                            <id>mojo-descriptor</id>
                            <goals>
                                <goal>descriptor</goal>
                            </goals>
                        </execution>
                        <!-- if you want to generate help goal -->
                        <execution>
                            <id>help-goal</id>
                            <goals>
                                <goal>helpmojo</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <configuration>
                        <preparationGoals>clean install</preparationGoals>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.plexus</groupId>
                    <artifactId>plexus-component-metadata</artifactId>
                    <version>2.2.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.rat</groupId>
                    <artifactId>apache-rat-plugin</artifactId>
                    <version>0.18</version>
                    <configuration>
                        <inputExcludes>
                            <inputExclude>.gitignore</inputExclude>
                            <inputExclude>DEPENDENCIES</inputExclude>
                            <inputExclude>README.txt</inputExclude>
                            <inputExclude>*.sh</inputExclude>
                            <inputExclude>.git/**</inputExclude>
                            <inputExclude>.idea/**</inputExclude>
                            <inputExclude>out/**</inputExclude>
                            <inputExclude>.extract/**</inputExclude>
                            <inputExclude>*.patch</inputExclude>
                            <inputExclude>**/access_log.*</inputExclude>
                            <inputExclude>**/src/test/resources/**/goal.txt</inputExclude>
                            <inputExclude>**/src/test/resources/**/archetype.properties</inputExclude>
                        </inputExcludes>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-scm-publish-plugin</artifactId>
                    <configuration>
                        <pubScmUrl>scm:svn:https://svn.apache.org/repos/asf/tomcat/site/trunk/docs/${sitePath}</pubScmUrl>
                        <checkinComment>Apache Tomcat Maven Plugin site documentation for ${project.version}</checkinComment>
                        <content>${tomcat-maven.siteFilePath}</content>
                        <checkoutDirectory>${tomcat-maven.scmPubCheckoutDirectory}</checkoutDirectory>
                        <tryUpdate>true</tryUpdate>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.rat</groupId>
                <artifactId>apache-rat-plugin</artifactId>
                <executions>
                    <execution>
                        <id>rat-verify</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>enforce-java</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireJavaVersion>
                                    <version>1.7.0</version>
                                </requireJavaVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-component-metadata</artifactId>
                <executions>
                    <execution>
                        <id>process-classes</id>
                        <goals>
                            <goal>generate-metadata</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <unzip src="src/test/manager.war" dest="${managerWebAppPath}" />
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-invoker-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <pomIncludes>
                                <include>**/simple-war-exec-project/pom.xml</include>
                            </pomIncludes>
                            <showErrors>true</showErrors>
                            <localRepositoryPath>${basedir}/target/it-repo</localRepositoryPath>
                            <settingsFile>src/it/settings.xml</settingsFile>
                            <postBuildHookScript>verify</postBuildHookScript>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>

        <dependency>
            <groupId>org.eclipse.jdt</groupId>
            <artifactId>ecj</artifactId>
            <!-- Latest version that supports Java 8 -->
            <version>3.26.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.maven.plugin-tools</groupId>
            <artifactId>maven-plugin-annotations</artifactId>
            <version>${mavenPluginPluginVersion}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-plugin-api</artifactId>
            <version>${mavenVersion}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.wagon</groupId>
            <artifactId>wagon-provider-api</artifactId>
            <version>3.5.3</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-artifact</artifactId>
            <version>${mavenVersion}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-model</artifactId>
            <version>${mavenVersion}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-core</artifactId>
            <version>${mavenVersion}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-compat</artifactId>
            <scope>provided</scope>
            <version>${mavenVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-archiver</artifactId>
            <version>3.6.6</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.shared</groupId>
            <artifactId>maven-filtering</artifactId>
            <version>3.5.0</version>
            <exclusions>
                <exclusion>
                    <groupId>nekohtml</groupId>
                    <artifactId>xercesMinimal</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>1.11.0</version>
        </dependency>

        <!-- Test Dependencies -->

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
        </dependency>
        <dependency>
            <groupId>junit-addons</groupId>
            <artifactId>junit-addons</artifactId>
            <version>1.4</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.shared</groupId>
            <artifactId>maven-verifier</artifactId>
            <version>1.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.14</version>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-util</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-coyote</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-jasper</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-jasper-el</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-el-api</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-catalina</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-tribes</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-catalina-ha</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-annotations-api</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-juli</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-servlet-api</artifactId>
            <version>${tomcatVersion}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-jsp-api</artifactId>
            <version>${tomcatVersion}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-jdbc</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-dbcp</artifactId>
            <version>${tomcatVersion}</version>
        </dependency>

    </dependencies>

    <distributionManagement>
        <repository>
            <id>apache.releases.https</id>
            <name>Apache Release Distribution Repository</name>
            <url>${distributionReleaseUrl}</url>
        </repository>

        <snapshotRepository>
            <id>${distributionIdSnapshots}</id>
            <name>Apache Development Snapshot Repository</name>
            <url>${distributionSnapshotsUrl}</url>
        </snapshotRepository>
        <site>
            <id>apache.website</id>
            <url>${tomcat-maven.siteUrlDeployment}</url>
        </site>
    </distributionManagement>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>3.9.0</version>
                <configuration>
                    <linkOnly>true</linkOnly>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-plugin-plugin</artifactId>
                <version>${mavenPluginPluginVersion}</version>
                <configuration>
                    <requirements>
                        <jdk>${maven.compiler.target}</jdk>
                    </requirements>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.12.0</version>
                <inherited>false</inherited>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>aggregate</report>
                        </reports>
                    </reportSet>
                </reportSets>
                <configuration>
                    <links>
                        <link>http://tomcat.apache.org/tomcat-9.0-doc/api/</link>
                    </links>
                    <detectLinks>true</detectLinks>
                    <notimestamp>true</notimestamp>
                    <tagletArtifacts>
                        <tagletArtifact>
                            <groupId>org.apache.maven.plugin-tools</groupId>
                            <artifactId>maven-plugin-tools-javadoc</artifactId>
                            <version>3.2</version>
                        </tagletArtifact>
                        <tagletArtifact>
                            <groupId>org.codehaus.plexus</groupId>
                            <artifactId>plexus-javadoc</artifactId>
                            <version>1.0</version>
                        </tagletArtifact>
                    </tagletArtifacts>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-changes-plugin</artifactId>
                <version>2.12.1</version>
                <inherited>false</inherited>
                <configuration>
                    <columnNames>Type,Fix
                        Version,Key,Summary,Assignee,Status,Created</columnNames>
                    <maxEntries>200</maxEntries>
                    <onlyCurrentVersion>true</onlyCurrentVersion>
                    <resolutionIds>Fixed</resolutionIds>
                    <sortColumnNames>Type</sortColumnNames>
                    <!--fixVersionIds>12320767</fixVersionIds-->
                    <useJql>true</useJql>
                </configuration>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>jira-report</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>

    <profiles>

        <profile>
            <id>site-release</id>
            <properties>
                <sitePath>maven-plugin-${project.version}</sitePath>
            </properties>
        </profile>
        <profile>
            <id>reporting</id>
            <reporting>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-pmd-plugin</artifactId>
                        <version>3.28.0</version>
                        <configuration>
                            <targetJdk>${maven.compiler.target}</targetJdk>
                            <rulesets>
                                <ruleset>rulesets/maven.xml</ruleset>
                            </rulesets>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-checkstyle-plugin</artifactId>
                        <version>3.6.0</version>
                        <configuration>
                            <configLocation>config/maven_checks.xml</configLocation>
                            <headerLocation>config/maven-header.txt</headerLocation>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jxr-plugin</artifactId>
                        <version>3.6.0</version>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.sonar-plugins</groupId>
                        <artifactId>maven-report</artifactId>
                        <version>0.1</version>
                    </plugin>
                </plugins>
            </reporting>
        </profile>

        <profile>
            <id>tc-staging</id>
            <properties>
                <tcStagedReleaseUrl />
            </properties>
            <repositories>
                <repository>
                    <id>tc-staged</id>
                    <url>${tcStagedReleaseUrl}</url>
                </repository>
            </repositories>
        </profile>

    </profiles>

</project>